package org.apache.activemq.replica.plugin;

public enum ReplicaEventType {
    DESTINATION_UPSERT,
    DESTINATION_DELETE,
    MESSAGE_SEND,
    MESSAGE_ACK,
    MESSAGE_CONSUMED,
    MESSAGE_DISCARDED,
    TRANSACTION_BEGIN,
    TRANSACTION_PREPARE,
    TRANSACTION_ROLLBACK,
    TRANSACTION_COMMIT,
    TRANSACTION_FORGET, MESSAGE_EXPIRED;
}
